export const GET_ALL_PRODUCT_DATA_SUCCESS = "GET_ALL_PRODUCT_DATA_SUCCESS";
export const GET_ALL_PRODUCT_DATA_FAILED = "GET_ALL_PRODUCT_DATA_FAILED";

export const GET_PRODUCT_DATA = "GET_PRODUCT_DATA";


