export const tbl = [
  // { header: "Item Image", field: "ItemImage", width: 250 },
  { header: "Item Name", field: "ItemName", width: 250, cell: "autocomplete" },
  { header: "Item Code", field: "ItemCode", width: 150, cell: "autocomplete" },
  { header: "Remarks", field: "Remarks", cell: "EditInput" },
  { header: "Unit", field: "unit" },
  { header: "Quantity", field: "Qty", cell: "EditInput" },
  { header: "Rate", field: "Rate", cell: "EditInput" },
  { header: "Disc(%)", field: "Disper", cell: "EditInput" },
  { header: "Discount Amount", field: "DisAmount" },
  { header: "Gross Total", field: "Gtotal" },
  { header: "Net Total", field: "Ntotal" },
];
export const tblindent = [
  // { header: "Item Image", field: "ItemImage", width: 250 },
  { header: "Item Name", field: "ItemName", width: 250 },
  { header: "Item Code", field: "ItemCode", width: 150 },
  { header: "Remarks", field: "Remarks", cell: "EditInput" },
  { header: "Unit", field: "unit" },
  { header: "Quantity", field: "Qty", cell: "EditInput" },
  { header: "Rate", field: "Rate", cell: "EditInput" },
  { header: "Disc(%)", field: "Disper", cell: "EditInput" },
  { header: "Discount Amount", field: "DisAmount" },
  { header: "Gross Total", field: "Gtotal" },
  { header: "Net Total", field: "Ntotal" },
];
export const popuptbl = [
  { header: "Indent No", field: "IndentNo", width: 150 },
  { header: "Indent Date", field: "IndentDate" },
  { header: "Item Code", field: "ItemCode", width: 150 },
  { header: "Item Name", field: "ItemName", width: 250 },
  { header: "Pending Qty", field: "pQty" },
  { header: "Pending Alt Qty", field: "pAltqty" },
  { header: "PO Qty", field: "poQty", cell: "EditInput" },
  { header: "PO Alt Qty", field: "poAltQty" },
];
