const coulmn = [
  {
    header: "Product Code",
    field: "ItemCode",
    width: 150,
  },
  {
    header: "Product Name",
    field: "ItemName",
    width: 250,
  },
  { header: "Qty", field: "quantity", cell: "EditInput" },
  { header: "MRP", field: "mrp" },
  { header: "Sale Price", field: "saleprice" },
  { header: "Gross Amount", field: "grossAmount" },
  { header: "Auto Discount(%)", field: "autodiscountper" },
  { header: "Auto Discount Amount", field: "autodiscountamount" },
  { header: "Manual Discount(%)", field: "manualdiscountper" },
  { header: "Manual Discount Amount", field: "manualdiscountamount" },
  { header: "Tax Per", field: "taxper" },
  { header: "Tax Amount", field: "taxamount" },
  { header: "Additional Tax", field: "addtaxrate" },
  { header: "Additional TaxAmount", field: "addtaxamount" },
  { header: "Surcharge On Tax", field: "surchargerate" },
  { header: "Surcharge On Tax Amount", field: "surchargeamount" },
  { header: "Total Tax Amount", field: "totaltaxamount" },
  { header: "Amount", field: "amount" },
  { header: "Lot No", field: "lotno" },
  { header: "Sale Person", field: "salepersonid" },
  { header: "item Remark", field: "itemremark" },
  { header: "IGST Rate %", field: "igstrate" },
  { header: "IGST Amount", field: "igstamount" },
  { header: "CGST Rate %", field: "cgstrate" },
  { header: "CGST Amount", field: "cgstamount" },
  { header: "SGST Rate %", field: "sgstrate" },
  { header: "SGST Amount", field: "sgstamount" },
];
export default coulmn;
